feat: Changed approach to from webhook to pulling
santander-digital-assets/terraform-aws-github-runner pull request #1
Opened 2020-08-25 14:35 UTC by n500004

The approach was changed from webhook to pulling based.

2020-08-26 08:53 UTC, fdelamor requested changes

2020-08-26 08:53 UTC, fdelamor commented on variables.tf
> +
"market_options" sólo puede valer "spot". ¿No es más usable tener un bool para activar "spot" instances?

2020-08-26 08:53 UTC, fdelamor commented on variables.tf
> +  default     = "cron(*/5 * * * ? *)"
¿No sería '*/5 * *  ? * * *' ?
Polling cada 5s por defecto parece muy agresivo. Yo lo bajaría al menos cada minuto ('* 0/1 0 ? * * *')

2020-08-26 08:53 UTC, fdelamor commented on modules/runners/variables.tf
> +  default     = "cron(*/5 * * * ? *)"
Ya tiene un default en el módulo principal. No es necesario en el módulo anidado.

2020-08-26 08:53 UTC, fdelamor commented on modules/runners/policies/lambda-scale-up.json
> +      "Resource": "arn:aws:iam::*:role/aws-service-role/*"
No entiendo mucho de permisos aws pero... ¿esos '*' no son demasiado "permisivos?

2020-08-26 08:53 UTC, fdelamor commented on modules/runners/README.md
> +| scale\_up\_schedule\_expression | Scheduler expression to check every x for scale up. | `string` | `"cron(*/5 * * * ? *)"` | no |
¿[scale up o scale out](https://packetpushers.net/scale-up-vs-scale-out/#:~:text=Scaling%20out%20%3D%20adding%20more%20components,it%20can%20handle%20more%20load.)?

2020-08-26 08:53 UTC, fdelamor commented on modules/runners/README.md
> +| scale\_up\_schedule\_expression | Scheduler expression to check every x for scale up. | `string` | `"cron(*/5 * * * ? *)"` | no |
¿y que hay del cron del scale-in?

2020-08-26 08:53 UTC, fdelamor commented on variables.tf
>  variable "runners_lambda_zip" {
¿Cada autoscale group de runners pone a correr sus propias lambdas a partir de los fuentes?
imagina que tengo uno para dockers, otro para windows y otro para linux. ¿No debería ser el lambda una dependencia compartida por todos ellos?

2020-08-26 12:48 UTC, n500004 commented on versions.tf
> +    aws = ">= 3.0"
Eso quedo tal cual estaba en el repo original, lo podemos bajar pero no entiendo porque traería problemas de incompatibilidad.

2020-08-26 13:09 UTC, n500004 commented on variables.tf
>  variable "runners_lambda_zip" {
No entiendo bien la pregunta. Hay dos lambdas que corren cada x tiempo y escalan hacia adentro o afuera segun sea el caso.

2020-08-26 13:12 UTC, n500004 commented on modules/runners/policies/lambda-scale-up.json
> +      "Resource": "arn:aws:iam::*:role/aws-service-role/*"
Eso solo permite crear ServiceLinkedRoles, que son los roles que usan los servicios por defecto para hacer sus cosas. Como por defecto no vienen todos creados, la primera vez que usas un servicio se deben crear. Entonces, eso permite que la lambda cree los ServiceLinkedRoles que sean necesarios.

2020-08-26 13:16 UTC, n500004 commented on modules/runners/README.md
> +| scale\_up\_schedule\_expression | Scheduler expression to check every x for scale up. | `string` | `"cron(*/5 * * * ? *)"` | no |
En este caso es scale-out, no lo he cambiado porque intento cambiar lo menos posible el código original. Como puedes ver en los [códigos](https://github.com/santander-digital-assets/tfdeploy-aws-runnersgithub/blob/master/main.tf#L191) nativos que he desarrollado yo, les he puesto el nombre como corresponde.

2020-08-26 13:17 UTC, n500004 commented on modules/runners/scale-up.tf
> +  name = "${var.environment}-lambda-scale-down-policy"
En este caso es scale-out, no lo he cambiado porque intento cambiar lo menos posible el código original. Como puedes ver en los [códigos](https://github.com/santander-digital-assets/tfdeploy-aws-runnersgithub/blob/master/main.tf#L191) nativos que he desarrollado yo, les he puesto el nombre como corresponde.

2020-08-26 13:36 UTC, n500004 commented on variables.tf
> +  default     = "cron(*/5 * * * ? *)"
Esa expresión indica cada 5 minutos: [cron-parser](https://www.npmjs.com/package/cron-parser)

2020-08-26 13:40 UTC, n500004 commented on modules/runners/variables.tf
> +  default     = "cron(*/5 * * * ? *)"
Son necesarios porque los módulos se desarrollan completamente por separado y luego se integran. Te paso otro ejemplo:
https://github.com/santander-digital-assets/terraform-aws-github-runner/blob/develop/variables.tf#L126
https://github.com/santander-digital-assets/terraform-aws-github-runner/blob/develop/modules/runners/variables.tf#L168

2020-08-27 11:25 UTC, n500004 commented on variables.tf
> +
Muy cierto, lo he dejado como string (tal como viene en el repo original) porque parece que aws tiene pensado añadir mas options a futuro:
--instance-market-options (structure)

The market (purchasing) option for the instances.

For RunInstances , persistent Spot Instance requests are only supported when InstanceInterruptionBehavior is set to either hibernate or stop .

2020-09-29 08:44 UTC, merged